# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "codelab-monitor"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: prometheus

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      # - targets: ["localhost:9090"]
      - targets:
          - 192.168.100.145:9800
          - 192.168.100.167:9100

  - job_name: docker
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

    static_configs:
      - targets: ["192.168.100.145:9323"]
  
  - job_name: cadvisor
    static_configs:
      - targets:
          - '192.168.100.145:8080'  # Assuming cAdvisor is running on this IP and port
  
  - job_name: blackbox
    metrics_path: /probe
    scrape_interval: 5s
    params:
      module: [http_2xx]
    static_configs:
    - targets:
      - https://www.southtechgroup.com
      - https://zzflscaled.southtechgroup.com:99
      - https://allexpharma.southtechgroup.com:7098
      - https://amepos.southtechgroup.com:9070
      - https://amepos.southtechgroup.com:9071
      - https://amepos.southtechgroup.com:9072
      - https://amepos.southtechgroup.com:9073
      - https://amepos.southtechgroup.com:9074
      - https://amepos.southtechgroup.com:9075
      - https://amepos.southtechgroup.com:9076
      - https://amepos.southtechgroup.com:9077
      - https://amepos.southtechgroup.com:9078
      - https://amepos.southtechgroup.com:9080
      - https://amepos.southtechgroup.com:9081
      - https://amepos.southtechgroup.com:9082
      - https://wazibpharma.southtechgroup.com:4098
      - https://wazibpharma.southtechgroup.com:4099
      - https://wazibpharma.southtechgroup.com:4097
      - https://rmepos.southtechgroup.com:5020
      - http://rmepos.southtechgroup.com:5021
      - https://rmepos.southtechgroup.com:5022

    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 192.168.100.145:9115